#!/bin/bash
if [[ ! -d "$HOME/.trash" ]]
then
	mkdir "$HOME/.trash"
fi

if [[ ! -e "$HOME/.trash/.num" ]]
then
	echo 1 > "$HOME/.trash/.num"
fi

if [[ $# != 1 ]]
then
	echo "There should be only 1 argument"
	exit 1
fi

if [[ ! -f  $1 ]]
then
	echo "No such file in this directory"
fi

num=$(cat "$HOME/.trash/.num")
ln ./$1 "$HOME/.trash/$num"
touch "$HOME/.trash/$num"
rm ./$1
echo "$PWD/$1 $HOME/.trash/$num" >> "$HOME/.trash.log"
let 'num=num+1'
echo $num > "$HOME/.trash/.num"
